https://www.kaggle.com/datasets/rtatman/questionanswer-dataset/data?select=S08_question_answer_pairs.txt

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('data/text-data/S08_question_answer_pairs.txt',sep='\t')
df1

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
...,...,...,...,...,...,...
1710,Woodrow_Wilson,Was Wilson president of the American Political...,Yes,NaN,easy,S08_set3_a8
1711,Woodrow_Wilson,Did he not cast his ballot for John M. Palmer ...,Yes,NaN,easy,S08_set3_a8
1712,Woodrow_Wilson,Did Wilson not spend 1914 through the beginnin...,Yes,NaN,easy,S08_set3_a8
1713,Woodrow_Wilson,"Was Wilson , a staunch opponent of antisemitis...",Yes,NaN,easy,S08_set3_a8


In [3]:
df2 = pd.read_csv('data/text-data/S09_question_answer_pairs.txt',sep='\t')
df2

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
1,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
2,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
3,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
4,Alessandro_Volta,Did Volta have a passion for the study of elec...,yes,easy,medium,S09_set4_a10
...,...,...,...,...,...,...
820,Xylophone,What is the earliest historical reference in E...,Arnold Schlick's Spiegel der Orgelmacher und O...,medium,medium,S09_set2_a8
821,Xylophone,How are western-style xylophones characterised?,"by a bright, sharp tone and high register",medium,medium,S09_set2_a8
822,Xylophone,Can a xylophone be 3 octaves?,yes,hard,hard,S09_set2_a8
823,Xylophone,Can a short bar follow a long bar?,no,hard,hard,S09_set2_a8


In [4]:
df3 = pd.read_csv('data/text-data/S10_question_answer_pairs.txt',sep='\t',encoding='latin-1')
df3

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,Alessandro Volta was not a professor of chemis...,easy,easy,S10_set4_a10
1,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,No,easy,hard,S10_set4_a10
2,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...,easy,easy,S10_set4_a10
3,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Yes,easy,easy,S10_set4_a10
4,Alessandro_Volta,Was Alessandro Volta taught in public schools?,Volta was taught in public schools.,easy,easy,S10_set4_a10
...,...,...,...,...,...,...
1453,Zebra,What areas do the Grevy's Zebras inhabit?,NaN,hard,NaN,S10_set1_a9
1454,Zebra,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur...",hard,medium,S10_set1_a9
1455,Zebra,Which species of zebra is known as the common ...,Plains Zebra,hard,medium,S10_set1_a9
1456,Zebra,At what age can a zebra breed?,five or six,hard,medium,S10_set1_a9


In [5]:
df1.shape,df2.shape,df3.shape

((1715, 6), (825, 6), (1458, 6))

In [6]:
1715 + 825 + 1458

3998

In [7]:
df = pd.concat(
    [df1,df2,df3],axis=0
)[['Question','Answer']]

In [8]:
df

,Question,Answer
0,Was Abraham Lincoln the sixteenth President of...,yes
1,Was Abraham Lincoln the sixteenth President of...,Yes.
2,Did Lincoln sign the National Banking Act of 1...,yes
3,Did Lincoln sign the National Banking Act of 1...,Yes.
4,Did his mother die of pneumonia?,no
...,...,...
1453,What areas do the Grevy's Zebras inhabit?,NaN
1454,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur..."
1455,Which species of zebra is known as the common ...,Plains Zebra
1456,At what age can a zebra breed?,five or six


In [9]:
sum(df['Answer'].value_counts().head(6).values)

np.int64(1367)

In [10]:
df.isnull().sum()

Question     37
Answer      578
dtype: int64

In [11]:
df = df.dropna(axis=0)

In [12]:
df.shape

(3420, 2)

In [13]:
df = df.sample(200).reset_index(drop=True)

In [14]:
df

,Question,Answer
0,Is it true that he sent in federal troops to c...,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hered..."
...,...,...
195,Did James Monroe attend the College of William...,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.


In [18]:
import re

In [19]:
def tokenize(text):
    if isinstance(text, str): 
        text = text.lower()
        
        # We added \d to the brackets to catch all numbers
        # Alternatively, you could write 0-9 inside the brackets
        text = re.sub(r'[!-@#$%^&*()_+><:;?\'\d]', '', text)
        
        return text.split()
    return text

In [20]:
tokenize(df['Question'][0])

['is',
 'it',
 'true',
 'that',
 'he',
 'sent',
 'in',
 'federal',
 'troops',
 'to',
 'chicago']

In [21]:
# Vocab

vocab = {'<PAD>':0,'SOS':1,'EOS':2,'<UNK>':3}

In [22]:
def build_vocab(row):

    tokenized_question = tokenize(row['Question'])
    tokenized_answer = tokenize(row['Answer'])

    for token in tokenized_question + tokenized_answer:
        if token not in vocab:
            vocab[token] = len(vocab)

In [23]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ... 
195    None
196    None
197    None
198    None
199    None
Length: 200, dtype: object

In [24]:
len(vocab)

1057

In [27]:
vocab

{'<PAD>': 0,
 'SOS': 1,
 'EOS': 2,
 '<UNK>': 3,
 'is': 4,
 'it': 5,
 'true': 6,
 'that': 7,
 'he': 8,
 'sent': 9,
 'in': 10,
 'federal': 11,
 'troops': 12,
 'to': 13,
 'chicago': 14,
 'yes': 15,
 'was': 16,
 'amedeo': 17,
 'avogadro': 18,
 'born': 19,
 'turin': 20,
 'what': 21,
 'happened': 22,
 'the': 23,
 'early': 24,
 'th': 25,
 'century': 26,
 'koalas': 27,
 'of': 28,
 'south': 29,
 'australia': 30,
 'were': 31,
 'largely': 32,
 'exterminated': 33,
 'are': 34,
 'reasons': 35,
 'for': 36,
 'hunting': 37,
 'wild': 38,
 'ducks': 39,
 'meat': 40,
 'eggs': 41,
 'and': 42,
 'feathers': 43,
 'has': 44,
 'tusklessness': 45,
 'become': 46,
 'a': 47,
 'rare': 48,
 'abnormality': 49,
 'no': 50,
 'widespread': 51,
 'hereditary': 52,
 'trait': 53,
 'does': 54,
 'each': 55,
 'type': 56,
 'drum': 57,
 'head': 58,
 'serve': 59,
 'its': 60,
 'own': 61,
 'musical': 62,
 'purpose': 63,
 'nineteen': 64,
 'fifty': 65,
 'seven': 66,
 'maynard': 67,
 'ferguson': 68,
 'formed': 69,
 'his': 70,
 'band': 71

In [28]:
def text_to_indices(text, vocab,add_eos=False):

    indices = [
        vocab.get(token,vocab['<UNK>'])
        for token in tokenize(text)
    ]
    if add_eos:
        indices.append(vocab['EOS'])
    return indices

In [29]:
df['Question'][0].split()

['Is',
 'it',
 'true',
 'that',
 'he',
 'sent',
 'in',
 'federal',
 'troops',
 'to',
 'chicago?']

In [32]:
text_to_indices(df['Question'][0],vocab)

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [33]:
df

,Question,Answer
0,Is it true that he sent in federal troops to c...,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hered..."
...,...,...
195,Did James Monroe attend the College of William...,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.


In [34]:
df.iloc[0]['Question']

'Is it true that he sent in federal troops to chicago?'

In [36]:
import torch
from torch.utils.data import DataLoader , Dataset

In [37]:
class QADataset(Dataset):

    def __init__(self,df,vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self,index):

        numerical_question = text_to_indices(self.df.iloc[index]['Question'],self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['Answer'],self.vocab,add_eos=True)

        return torch.tensor(numerical_question) , torch.tensor(numerical_answer)

In [38]:
dataset = QADataset(df,vocab) 

In [39]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [40]:
for question , answer in dataloader:
    print(question,answer[0])

tensor([[ 54, 263, 506,  47, 507, 329, 508]]) tensor([15,  2])
tensor([[  4,  23, 800, 975, 976,  42, 977,  74, 378, 443, 978, 979, 980]]) tensor([15,  2])
tensor([[ 21, 134, 152,  23, 576,  28,  47, 577,   4, 578]]) tensor([  5, 579,  47, 580, 117,   4,  10,  47, 581, 582, 342,  23, 583,  28,
         23, 577,   2])
tensor([[ 21,  92, 904, 749, 905, 129, 906, 584]]) tensor([ 47, 584, 585,  47, 907, 304,  47, 908,   2])
tensor([[152,  16,   8,  73, 653,  28, 654, 655, 149, 150]]) tensor([15,  2])
tensor([[312,  92, 660,  98,  47, 661, 662, 580]]) tensor([ 23, 348,  42, 663, 506,  47, 664, 665, 666,   2])
tensor([[122, 123,  23, 918,  10,  21, 546, 141,  23, 919, 920, 921, 922,  10,
         490]]) tensor([2])
tensor([[  21,  153,  836,  831, 1017,  127,   23,  627,   28,  629]]) tensor([1018,  329,  631,  632,    2])
tensor([[  4,  23, 466, 467, 468,  10, 469]]) tensor([15,  2])
tensor([[  4,   5,   6,   7,   8, 470,  47, 284,  10]]) tensor([15,  2])
tensor([[184,  92, 235, 459, 460, 4

In [35]:
# X = nn.Embedding(544,embedding_dim=50)
# Y = nn.RNN(50,64,batch_first = True)
# Z = nn.Linear(64,544)

# # step 1 data

# a = dataset[0][0].reshape(1,3)
# print(f"Shape of a: {a.shape}")
# b = X(a) # 50 dim
# print(f"Shape of b: {b.shape}")
# c , d = Y(b) # RNN
# print(f"Shape of c :{c.shape} \nShape of d : {d.shape}")

# e = Z(d.squeeze(0))
# print(f"Shape of e: {e.shape}")

In [42]:
import torch.nn as nn

In [60]:
a = torch.tensor(text_to_indices(df['Question'][0],vocab))
torch.ones(len(a),1,dtype=torch.long).shape

torch.Size([11, 1])

In [64]:
df

,Question,Answer
0,Is it true that he sent in federal troops to c...,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hered..."
...,...,...
195,Did James Monroe attend the College of William...,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.


In [71]:
torch.tensor(text_to_indices(df['Answer'][2],vocab))

tensor([23, 27, 28, 29, 30, 31, 32, 33])

In [87]:
# Model Building 
# Simple RNN

class Seq2SeqRNN(nn.Module):
    def __init__(self,vocab_size,embed_dim=50,hidden_dim = 64):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,embed_dim)
        self.encoder = nn.RNN(embed_dim,hidden_dim,batch_first=True)
        self.decoder = nn.RNN(embed_dim,hidden_dim,batch_first=True)
        self.fc = nn.Linear(hidden_dim,vocab_size)

    def forward(self,question,answer=None,max_len=10):

        # Encoder
        embedded_q = self.embedding(question)
        _ , hidden = self.encoder(embedded_q)

        # Decoder - <SOS> token
        batch_size = question.size(0)
        decoder_input = torch.ones(batch_size , 1 , dtype=torch.long)

        outputs = []
        seq_len = answer.size(1) if answer is not None else max_len

        for i in range(seq_len):
            embedded_d = self.embedding(decoder_input)
            out , hidden = self.decoder(embedded_d,hidden)
            prediction = self.fc(out.squeeze(1))  # [1,vocab_size]
            outputs.append(prediction)

            if answer is not None:
                decoder_input = answer[:,i].unsqueeze(1)  # teacher forcing
            else:
                decoder_input = prediction.argmax(dim=1).unsqueeze(1)
        return torch.stack(outputs,dim=1)   # [1,seq_len , vocab_size]

In [88]:
learning_rate = 0.001
epochs = 100

In [89]:
model = Seq2SeqRNN(len(vocab))

In [90]:
# loss , optimizer 

criterion = nn.CrossEntropyLoss(ignore_index=0)
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [91]:
# for q,a in dataloader:
#     print(a)
#     print("1d :-",a.flatten())
#     print("scaler vaule :-",a.flatten()[0])
#     print("unsqueeze(0)  :-",a.flatten()[0].unsqueeze(0) )
#     break

In [92]:
# Training Loop


for epoch in range(epochs):
    total_loss =0 

    for question , answer in dataloader:
        if answer.numel() == 0:
            continue
        optimizer.zero_grad()

        output = model(question,answer)
        output_flat = output.view(-1,len(vocab)) # [1,seq_len,vocab_size]
        target_flat = answer.view(-1)
    
        loss = criterion(output_flat , target_flat)
        loss.backward()

        optimizer.step()

        total_loss += loss.item()
    print(f"Epoch : {epoch+1} , Loss : {total_loss:.4f}")

Epoch : 1 , Loss : 914.4972
Epoch : 2 , Loss : 653.8432
Epoch : 3 , Loss : 591.7310
Epoch : 4 , Loss : 530.3949
Epoch : 5 , Loss : 475.7310
Epoch : 6 , Loss : 425.7673
Epoch : 7 , Loss : 380.6088
Epoch : 8 , Loss : 339.6999
Epoch : 9 , Loss : 299.7884
Epoch : 10 , Loss : 261.6678
Epoch : 11 , Loss : 226.1390
Epoch : 12 , Loss : 194.1989
Epoch : 13 , Loss : 165.3166
Epoch : 14 , Loss : 140.2509
Epoch : 15 , Loss : 119.5130
Epoch : 16 , Loss : 100.7690
Epoch : 17 , Loss : 85.0672
Epoch : 18 , Loss : 71.7296
Epoch : 19 , Loss : 61.0800
Epoch : 20 , Loss : 51.9520
Epoch : 21 , Loss : 44.1547
Epoch : 22 , Loss : 37.4845
Epoch : 23 , Loss : 32.3079
Epoch : 24 , Loss : 28.1208
Epoch : 25 , Loss : 24.1587
Epoch : 26 , Loss : 20.6474
Epoch : 27 , Loss : 17.9212
Epoch : 28 , Loss : 15.4740
Epoch : 29 , Loss : 13.7958
Epoch : 30 , Loss : 11.9280
Epoch : 31 , Loss : 10.5868
Epoch : 32 , Loss : 9.3050
Epoch : 33 , Loss : 8.5918
Epoch : 34 , Loss : 7.7899
Epoch : 35 , Loss : 7.1410
Epoch : 36 , Loss

In [46]:
Q_1 = model(torch.tensor(text_to_indices(df['Question'][0],vocab)).unsqueeze(0))
prob = torch.nn.functional.softmax(Q_1,dim=1)
torch.max(prob,dim=1)

torch.return_types.max(
values=tensor([0.9999], grad_fn=<MaxBackward0>),
indices=tensor([10]))

In [47]:
list(vocab)[5]

'is'

In [124]:
def predict(model,question,vocab,threshold=0.5,max_len=10):
    model.eval()
    index_to_word = {idx:word for word,idx in vocab.items()}

    with torch.no_grad():
        numberical_question = text_to_indices(question,vocab)
        
        # shape [1,seq_len]
        question_tensor = torch.tensor(numberical_question).unsqueeze(0)

        output = model(question_tensor,answer=None,max_len=max_len)

        # probabilities
        probs = torch.nn.functional.softmax(output,dim=2)
        value , index = torch.max(probs,dim=2)
        # print(f"Value :- {value},Index :- {index}")

        # answer in squance
        answer_words = []
        for i in range(index.size(1)):
            idx = index[0, i].item()
            confidence = value[0 , i].item()

            if idx == vocab.get('<EOS>',-1) or confidence < threshold:
                break

            answer_words.append(index_to_word.get(idx,'<UNK>'))
        
        answer = " ".join(answer_words)
        return f"Answer :- {answer}"

In [125]:
df

,Question,Answer
0,Is it true that he sent in federal troops to chicago?,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely exterminated.
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hereditary trait."
...,...,...
195,Did James Monroe attend the College of William and Mary?,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.


In [126]:
pd.set_option('display.max_colwidth', None)

In [131]:
def question_generate(dataframe , index=0):
    text = dataframe['Question'][index] 
    return text,df.iloc[[index]]

text , Q_A = question_generate(df,50)
print(text)
Q_A

Where are the only surviving giant tortoises?


,Question,Answer
50,Where are the only surviving giant tortoises?,Seychelles and Gal�pagos Islands


In [132]:
predict(model,text,vocab,threshold=0.5)

'Answer :- seychelles and gal�pagos islands EOS is'