https://www.kaggle.com/datasets/rtatman/questionanswer-dataset/data?select=S08_question_answer_pairs.txt

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('data/text-data/S08_question_answer_pairs.txt',sep='\t')
df1

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
...,...,...,...,...,...,...
1710,Woodrow_Wilson,Was Wilson president of the American Political...,Yes,NaN,easy,S08_set3_a8
1711,Woodrow_Wilson,Did he not cast his ballot for John M. Palmer ...,Yes,NaN,easy,S08_set3_a8
1712,Woodrow_Wilson,Did Wilson not spend 1914 through the beginnin...,Yes,NaN,easy,S08_set3_a8
1713,Woodrow_Wilson,"Was Wilson , a staunch opponent of antisemitis...",Yes,NaN,easy,S08_set3_a8


In [3]:
df2 = pd.read_csv('data/text-data/S09_question_answer_pairs.txt',sep='\t')
df2

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
1,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
2,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
3,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
4,Alessandro_Volta,Did Volta have a passion for the study of elec...,yes,easy,medium,S09_set4_a10
...,...,...,...,...,...,...
820,Xylophone,What is the earliest historical reference in E...,Arnold Schlick's Spiegel der Orgelmacher und O...,medium,medium,S09_set2_a8
821,Xylophone,How are western-style xylophones characterised?,"by a bright, sharp tone and high register",medium,medium,S09_set2_a8
822,Xylophone,Can a xylophone be 3 octaves?,yes,hard,hard,S09_set2_a8
823,Xylophone,Can a short bar follow a long bar?,no,hard,hard,S09_set2_a8


In [4]:
df3 = pd.read_csv('data/text-data/S10_question_answer_pairs.txt',sep='\t',encoding='latin-1')
df3

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,Alessandro Volta was not a professor of chemis...,easy,easy,S10_set4_a10
1,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,No,easy,hard,S10_set4_a10
2,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...,easy,easy,S10_set4_a10
3,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Yes,easy,easy,S10_set4_a10
4,Alessandro_Volta,Was Alessandro Volta taught in public schools?,Volta was taught in public schools.,easy,easy,S10_set4_a10
...,...,...,...,...,...,...
1453,Zebra,What areas do the Grevy's Zebras inhabit?,NaN,hard,NaN,S10_set1_a9
1454,Zebra,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur...",hard,medium,S10_set1_a9
1455,Zebra,Which species of zebra is known as the common ...,Plains Zebra,hard,medium,S10_set1_a9
1456,Zebra,At what age can a zebra breed?,five or six,hard,medium,S10_set1_a9


In [5]:
df1.shape,df2.shape,df3.shape

((1715, 6), (825, 6), (1458, 6))

In [6]:
1715 + 825 + 1458

3998

In [7]:
df = pd.concat(
    [df1,df2,df3],axis=0
)[['Question','Answer']]

In [8]:
df

,Question,Answer
0,Was Abraham Lincoln the sixteenth President of...,yes
1,Was Abraham Lincoln the sixteenth President of...,Yes.
2,Did Lincoln sign the National Banking Act of 1...,yes
3,Did Lincoln sign the National Banking Act of 1...,Yes.
4,Did his mother die of pneumonia?,no
...,...,...
1453,What areas do the Grevy's Zebras inhabit?,NaN
1454,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur..."
1455,Which species of zebra is known as the common ...,Plains Zebra
1456,At what age can a zebra breed?,five or six


In [9]:
sum(df['Answer'].value_counts().head(6).values)

np.int64(1367)

In [10]:
# words_to_remove = ['Yes', 'yes', 'Yes.', 'No', 'no', 'No.']
# df['Answer'] = df['Answer'].replace(words_to_remove, np.nan)

In [11]:
df.isnull().sum()

Question     37
Answer      578
dtype: int64

In [12]:
df = df.dropna(axis=0)

In [13]:
df.shape

(3420, 2)

In [14]:
df = df.sample(150).reset_index(drop=True)

In [15]:
df

,Question,Answer
0,What language besides Malay is in the Austrone...,Malagasy
1,What percentage of Liechtenstein's population ...,67%
2,What is the cause of local earthquakes?,It was the San Andreas Fault which slipped and...
3,Sea otters eat what?,Shellfish and other invertebrates
4,Was Calvin Coolidge Republican?,Yes
...,...,...
145,Has Urbanization eliminated many areas of form...,Yes
146,Is Vietnamese the mother tongue of the Vietnam...,Yes
147,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...
148,Is Swahili a Bantu language?,yes


In [16]:
import re

In [17]:
def tokenize(text):
    if isinstance(text, str): 
        text = text.lower()
        
        # We added \d to the brackets to catch all numbers
        # Alternatively, you could write 0-9 inside the brackets
        text = re.sub(r'[!-@#$%^&*()_+><:;?\'\d]', '', text)
        
        return text.split()
    return text

In [18]:
tokenize(df['Question'][0])

['what',
 'language',
 'besides',
 'malay',
 'is',
 'in',
 'the',
 'austronesia',
 'language',
 'family']

In [19]:
# Vocab (for unknow words)

vocab = {'<UNK>':0}

In [20]:
def build_vocab(row):
    # if pd.isna(row['Question']) or pd.isna(row['Answer']):
    #     return

    tokenized_question = tokenize(row['Question'])
    tokenized_answer = tokenize(row['Answer'])

    for token in tokenized_question + tokenized_answer:
        if token not in vocab:
            vocab[token] = len(vocab)

In [21]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ... 
145    None
146    None
147    None
148    None
149    None
Length: 150, dtype: object

In [22]:
len(vocab)

789

In [23]:
vocab

{'<UNK>': 0,
 'what': 1,
 'language': 2,
 'besides': 3,
 'malay': 4,
 'is': 5,
 'in': 6,
 'the': 7,
 'austronesia': 8,
 'family': 9,
 'malagasy': 10,
 'percentage': 11,
 'of': 12,
 'liechtensteins': 13,
 'population': 14,
 'foreignborn': 15,
 'cause': 16,
 'local': 17,
 'earthquakes': 18,
 'it': 19,
 'was': 20,
 'san': 21,
 'andreas': 22,
 'fault': 23,
 'which': 24,
 'slipped': 25,
 'and': 26,
 'caused': 27,
 'sea': 28,
 'otters': 29,
 'eat': 30,
 'shellfish': 31,
 'other': 32,
 'invertebrates': 33,
 'calvin': 34,
 'coolidge': 35,
 'republican': 36,
 'yes': 37,
 'canada': 38,
 'bilingual': 39,
 'prompted': 40,
 'city': 41,
 'to': 42,
 'upgrade': 43,
 'its': 44,
 'building': 45,
 'codes': 46,
 'threat': 47,
 'major': 48,
 'are': 49,
 'cougars': 50,
 'larger': 51,
 'than': 52,
 'jaguars': 53,
 'no': 54,
 'how': 55,
 'long': 56,
 'an': 57,
 'adult': 58,
 'paw': 59,
 'print': 60,
 'approximately': 61,
 'cm': 62,
 'inches': 63,
 'when': 64,
 'did': 65,
 'a': 66,
 'standard': 67,
 'common': 

In [24]:
def text_to_indices(text, vocab):

    return [
        vocab.get(token, vocab['<UNK>'])
        for token in tokenize(text)
    ]

In [25]:
df['Question'][0].split()

['What',
 'language',
 'besides',
 'Malay',
 'is',
 'in',
 'the',
 'Austronesia',
 'language',
 'family?']

In [26]:
text_to_indices(df['Question'][0],vocab)

[1, 2, 3, 4, 5, 6, 7, 8, 2, 9]

In [27]:
df

,Question,Answer
0,What language besides Malay is in the Austrone...,Malagasy
1,What percentage of Liechtenstein's population ...,67%
2,What is the cause of local earthquakes?,It was the San Andreas Fault which slipped and...
3,Sea otters eat what?,Shellfish and other invertebrates
4,Was Calvin Coolidge Republican?,Yes
...,...,...
145,Has Urbanization eliminated many areas of form...,Yes
146,Is Vietnamese the mother tongue of the Vietnam...,Yes
147,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...
148,Is Swahili a Bantu language?,yes


In [28]:
df.iloc[0]['Question']

'What language besides Malay is in the Austronesia language family?'

In [29]:
import torch
from torch.utils.data import DataLoader , Dataset

In [30]:
class QADataset(Dataset):

    def __init__(self,df,vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self,index):

        numerical_question = text_to_indices(self.df.iloc[index]['Question'],self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['Answer'],self.vocab)

        return torch.tensor(numerical_question) , torch.tensor(numerical_answer)

In [31]:
dataset = QADataset(df,vocab) 

In [32]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [33]:
for question , answer in dataloader:
    print(question,answer[0])

tensor([[  7, 552,  26, 553, 554,  20, 555, 211,  20,   7, 556, 557, 558,   6,
           1, 559]]) tensor([])
tensor([[ 75, 671, 672, 673]]) tensor([37])
tensor([[  1, 100, 101, 102, 103, 104, 105, 106]]) tensor([107,  26, 108])
tensor([[  1,  20,   7, 674,  12,  87,  88, 481]]) tensor([675, 676])
tensor([[  1,  65, 570, 729,  20, 211, 730, 211, 731]]) tensor([  7, 732, 133,   6, 733])
tensor([[  1,  65,  35,  75, 435, 765,  97, 766]]) tensor([ 35, 767,  42, 768, 769])
tensor([[  5,  87, 118, 533]]) tensor([ 54, 209,  20, 534])
tensor([[117,   5,   7,  87, 118, 119, 120]]) tensor([  7,  87, 118, 119,   5,   6, 121])
tensor([[117,  65,  66, 382, 383,  66, 384,   6]]) tensor([385, 220, 386])
tensor([[55, 56,  5, 57, 58, 50, 59, 60]]) tensor([57, 58, 50, 59, 60,  5, 61, 62, 63, 56])
tensor([[ 20, 453, 454,  66, 455, 162, 456,   6]]) tensor([ 37, 453,  20, 454,  66, 455, 162, 456,   6])
tensor([[  5, 266,  66,  41]]) tensor([37])
tensor([[204, 772, 773,  86, 295,  12, 774, 374, 775, 229, 

In [34]:
import torch.nn as nn

In [35]:
# X = nn.Embedding(544,embedding_dim=50)
# Y = nn.RNN(50,64,batch_first = True)
# Z = nn.Linear(64,544)

# # step 1 data

# a = dataset[0][0].reshape(1,3)
# print(f"Shape of a: {a.shape}")
# b = X(a) # 50 dim
# print(f"Shape of b: {b.shape}")
# c , d = Y(b) # RNN
# print(f"Shape of c :{c.shape} \nShape of d : {d.shape}")

# e = Z(d.squeeze(0))
# print(f"Shape of e: {e.shape}")

In [36]:
# Model Building 
# Simple RNN

class SimpleRNN(nn.Module):

    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,embedding_dim=50)
        self.rnn = nn.RNN(50,64,batch_first=True)
        self.fc = nn.Linear(64,vocab_size)

    def forward(self,question):
        embedded_question = self.embedding(question)
        hidden , final = self.rnn(embedded_question)
        output = self.fc(final.squeeze(0))

        return output

In [37]:
learning_rate = 0.001
epochs = 100

In [38]:
model = SimpleRNN(len(vocab))

In [39]:
# loss , optimizer 

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [41]:
# for q,a in dataloader:
#     print(a)
#     print("1d :-",a.flatten())
#     print("scaler vaule :-",a.flatten()[0])
#     print("unsqueeze(0)  :-",a.flatten()[0].unsqueeze(0) )
#     break

In [42]:
for epoch in range(epochs):
    total_loss = 0
    for question, answer in dataloader:

        if answer.numel() == 0:
            continue

        optimizer.zero_grad()

        output = model(question)                    # [1, vocab_size]
        target = answer.flatten()[0].unsqueeze(0)   # [1]  ← fixed

        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch: {epoch+1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 868.3240
Epoch: 2, Loss: 465.6113
Epoch: 3, Loss: 396.8719
Epoch: 4, Loss: 350.0307
Epoch: 5, Loss: 302.0195
Epoch: 6, Loss: 250.2417
Epoch: 7, Loss: 198.7329
Epoch: 8, Loss: 153.2116
Epoch: 9, Loss: 114.9199
Epoch: 10, Loss: 84.9141
Epoch: 11, Loss: 62.6070
Epoch: 12, Loss: 46.2117
Epoch: 13, Loss: 35.2285
Epoch: 14, Loss: 27.6426
Epoch: 15, Loss: 22.0569
Epoch: 16, Loss: 18.2186
Epoch: 17, Loss: 14.9094
Epoch: 18, Loss: 13.7570
Epoch: 19, Loss: 14.5334
Epoch: 20, Loss: 10.6004
Epoch: 21, Loss: 8.5726
Epoch: 22, Loss: 7.5448
Epoch: 23, Loss: 6.7718
Epoch: 24, Loss: 6.1429
Epoch: 25, Loss: 5.8813
Epoch: 26, Loss: 5.1502
Epoch: 27, Loss: 4.6561
Epoch: 28, Loss: 4.7439
Epoch: 29, Loss: 4.4728
Epoch: 30, Loss: 4.1863
Epoch: 31, Loss: 3.8673
Epoch: 32, Loss: 3.8118
Epoch: 33, Loss: 3.5999
Epoch: 34, Loss: 3.4684
Epoch: 35, Loss: 3.3060
Epoch: 36, Loss: 3.2018
Epoch: 37, Loss: 3.0979
Epoch: 38, Loss: 3.0012
Epoch: 39, Loss: 2.8537
Epoch: 40, Loss: 2.8186
Epoch: 41, Loss: 2.7

In [46]:
Q_1 = model(torch.tensor(text_to_indices(df['Question'][0],vocab)).unsqueeze(0))
prob = torch.nn.functional.softmax(Q_1,dim=1)
torch.max(prob,dim=1)

torch.return_types.max(
values=tensor([0.9999], grad_fn=<MaxBackward0>),
indices=tensor([10]))

In [47]:
list(vocab)[5]

'is'

In [48]:
def predict(model,question,vocab,threshold=0.5):
    model.eval()

    with torch.no_grad():
        numberical_question = text_to_indices(question,vocab)

        # shape [1,seq_len]
        question_tensor = torch.tensor(numberical_question).unsqueeze(0)

        output = model(question_tensor)

        # probabilities
        probs = torch.nn.functional.softmax(output,dim=1)

        # Get top probabilitie
        value , index = torch.max(probs,dim=1)
        print(f"Value :- {value},Index :- {index}")

        confidence = value.item()
        pred_idx = index.item()

        if confidence < threshold:
            print("I don't Know")
            return None
        # Answer 
        predicted_word = list(vocab.keys())[pred_idx]
        print(f'Predicted : {predicted_word} (confidence : {confidence:.2f})')
        return predicted_word

In [49]:
df

,Question,Answer
0,What language besides Malay is in the Austrone...,Malagasy
1,What percentage of Liechtenstein's population ...,67%
2,What is the cause of local earthquakes?,It was the San Andreas Fault which slipped and...
3,Sea otters eat what?,Shellfish and other invertebrates
4,Was Calvin Coolidge Republican?,Yes
...,...,...
145,Has Urbanization eliminated many areas of form...,Yes
146,Is Vietnamese the mother tongue of the Vietnam...,Yes
147,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...
148,Is Swahili a Bantu language?,yes


In [53]:
text = df['Question'][0] 

df['Question'][0] ," ",df['Answer'][0]

('What language besides Malay is in the Austronesia language family?',
 ' ',
 'Malagasy')

In [54]:
predict(model,text,vocab,threshold=0.5)

Value :- tensor([0.9999]),Index :- tensor([10])
Predicted : malagasy (confidence : 1.00)


'malagasy'