In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk
import re

In [2]:
file_paths = [
    "data/text-data/youtube/text_1.txt",
    "data/text-data/youtube/text_2.txt"
]

docs = []
for path in file_paths:
    with open(path, "r") as file:
        docs.append(file.read())

In [3]:
text = docs[0] + docs[1]

In [4]:
print(text)

Here's the AI news you might have missed this week. Oh, and by the way it might look like I'm in my normal studio right now. I'm actually in a hotel room here in Los Angeles. 


I'm out here for the Colin Samir Press publish LA event and definitely not shooting parts of this video on two separate days. 


Let's start with probably the biggest news of the week, which is the brand new model from anthropic. 


In their new Clod Opus 4.8 model, now, if I'm being totally honest, this is probably a fairly minor upgrade. 


I don't think most people are going to notice a huge difference from Opus 4.7 to 4.8, but here's what anthropic claims is different about this model. 


It's a little bit better at coding than 4.7, got a little boost on the benchmarks here, a little bit better at reasoning, very slightly better at computer use, and you know, just fairly modest boosts on the benchmarks. 


However, they do say one of the most prominent improvements in Opus 4.8. Is the honesty it's now bette

In [5]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /home/lenovo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/lenovo/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [6]:
def clean_text(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", "", text)
    return text
    
# Tokenize the cleaned text
tokens = word_tokenize(clean_text(text))
print(tokens)

['heres', 'the', 'ai', 'news', 'you', 'might', 'have', 'missed', 'this', 'week', 'oh', 'and', 'by', 'the', 'way', 'it', 'might', 'look', 'like', 'im', 'in', 'my', 'normal', 'studio', 'right', 'now', 'im', 'actually', 'in', 'a', 'hotel', 'room', 'here', 'in', 'los', 'angeles', 'im', 'out', 'here', 'for', 'the', 'colin', 'samir', 'press', 'publish', 'la', 'event', 'and', 'definitely', 'not', 'shooting', 'parts', 'of', 'this', 'video', 'on', 'two', 'separate', 'days', 'lets', 'start', 'with', 'probably', 'the', 'biggest', 'news', 'of', 'the', 'week', 'which', 'is', 'the', 'brand', 'new', 'model', 'from', 'anthropic', 'in', 'their', 'new', 'clod', 'opus', '48', 'model', 'now', 'if', 'im', 'being', 'totally', 'honest', 'this', 'is', 'probably', 'a', 'fairly', 'minor', 'upgrade', 'i', 'dont', 'think', 'most', 'people', 'are', 'going', 'to', 'notice', 'a', 'huge', 'difference', 'from', 'opus', '47', 'to', '48', 'but', 'heres', 'what', 'anthropic', 'claims', 'is', 'different', 'about', 'this',

In [7]:
def build_vocab(list_of_words):
    # bulid vocab
    vocab = {'<PAD>': 0, '<UNK>': 1}

    for token in Counter(list_of_words).keys():
        if token not in vocab:
            vocab[token] = len(vocab)
    return vocab

In [8]:
vocab = build_vocab(tokens)
vocab

{'<PAD>': 0,
 '<UNK>': 1,
 'heres': 2,
 'the': 3,
 'ai': 4,
 'news': 5,
 'you': 6,
 'might': 7,
 'have': 8,
 'missed': 9,
 'this': 10,
 'week': 11,
 'oh': 12,
 'and': 13,
 'by': 14,
 'way': 15,
 'it': 16,
 'look': 17,
 'like': 18,
 'im': 19,
 'in': 20,
 'my': 21,
 'normal': 22,
 'studio': 23,
 'right': 24,
 'now': 25,
 'actually': 26,
 'a': 27,
 'hotel': 28,
 'room': 29,
 'here': 30,
 'los': 31,
 'angeles': 32,
 'out': 33,
 'for': 34,
 'colin': 35,
 'samir': 36,
 'press': 37,
 'publish': 38,
 'la': 39,
 'event': 40,
 'definitely': 41,
 'not': 42,
 'shooting': 43,
 'parts': 44,
 'of': 45,
 'video': 46,
 'on': 47,
 'two': 48,
 'separate': 49,
 'days': 50,
 'lets': 51,
 'start': 52,
 'with': 53,
 'probably': 54,
 'biggest': 55,
 'which': 56,
 'is': 57,
 'brand': 58,
 'new': 59,
 'model': 60,
 'from': 61,
 'anthropic': 62,
 'their': 63,
 'clod': 64,
 'opus': 65,
 '48': 66,
 'if': 67,
 'being': 68,
 'totally': 69,
 'honest': 70,
 'fairly': 71,
 'minor': 72,
 'upgrade': 73,
 'i': 74,
 'dont'

In [9]:
len(vocab)

2130

In [13]:
cleaned_text = clean_text(text)

In [14]:
input_sentences = []

for i in cleaned_text.split('\n'):
    if len(i) > 0:
        input_sentences.append(i.strip())

In [15]:
input_sentences

['heres the ai news you might have missed this week oh and by the way it might look like im in my normal studio right now im actually in a hotel room here in los angeles',
 'im out here for the colin samir press publish la event and definitely not shooting parts of this video on two separate days',
 'lets start with probably the biggest news of the week which is the brand new model from anthropic',
 'in their new clod opus 48 model now if im being totally honest this is probably a fairly minor upgrade',
 'i dont think most people are going to notice a huge difference from opus 47 to 48 but heres what anthropic claims is different about this model',
 'its a little bit better at coding than 47 got a little boost on the benchmarks here a little bit better at reasoning very slightly better at computer use and you know just fairly modest boosts on the benchmarks',
 'however they do say one of the most prominent improvements in opus 48 is the honesty its now better at avoiding making claims 

In [16]:
def text_to_indices(sentence, vocab):

    numberical_sentence = []

    for token in sentence:
        if token in vocab:
            numberical_sentence.append(vocab[token])
        else:
            numberical_sentence.append(vocab['<UNK>'])
    return numberical_sentence

In [17]:
input_sentences[0]

'heres the ai news you might have missed this week oh and by the way it might look like im in my normal studio right now im actually in a hotel room here in los angeles'

In [18]:
input_numerical_sentences = []

for sentence in input_sentences:
    tokens = word_tokenize(sentence)
    input_numerical_sentences.append(text_to_indices(tokens,vocab))

In [19]:
len(input_numerical_sentences)

769

In [20]:
training_sequence = []

for encoded_sentence in input_numerical_sentences:
    # Loop through the sentence tokens to build incremental sequences
    for token_index in range(1, len(encoded_sentence)):
        sequence_prefix = encoded_sentence[:token_index + 1]
        training_sequence.append(sequence_prefix)

In [21]:
training_sequence

[[2, 3],
 [2, 3, 4],
 [2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [2, 3, 4, 5, 6, 7],
 [2, 3, 4, 5, 6, 7, 8],
 [2, 3, 4, 5, 6, 7, 8, 9],
 [2, 3, 4, 5, 6, 7, 8, 9, 10],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15, 16],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15, 16, 7],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15, 16, 7, 17],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15, 16, 7, 17, 18],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15, 16, 7, 17, 18, 19],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 15, 16, 7, 17, 18, 19, 20],
 [2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  3,
  15,
  16,
  7,
  17,
  18,
  19,
  20,
  21],
 [2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  1

In [22]:
len_list = []

for i in training_sequence:
    len_list.append(len(i))
max(len_list)

94

In [23]:
max_len = max(len_list)
padded_training_sequence = []

for sequence in training_sequence:
    seq_list = list(sequence) 
    padded_seq = [0] * (max_len - len(seq_list)) + seq_list
    padded_training_sequence.append(padded_seq)

In [24]:
len(padded_training_sequence[10])

94

In [25]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype =torch.long)

In [26]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        [  0,   0,   0,  ...,   3,   4,   5],
        ...,
        [  0,   0,   0,  ...,   3, 460, 114],
        [  0,   0,   0,  ...,   0, 944, 153],
        [  0,   0,   0,  ..., 944, 153, 145]])

In [27]:
X = padded_training_sequence[:,:-1]
y = padded_training_sequence[:,-1]

In [28]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   2],
        [  0,   0,   0,  ...,   0,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0,   0,  ...,  20,   3, 460],
        [  0,   0,   0,  ...,   0,   0, 944],
        [  0,   0,   0,  ...,   0, 944, 153]])

In [29]:
y

tensor([  3,   4,   5,  ..., 114, 153, 145])

In [30]:
class CustomDataset(Dataset):

    def __init__(self,X,y):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self,idx):
        return self.X[idx], self.y[idx]

In [31]:
dataset = CustomDataset(X,y)

In [32]:
len(dataset)

12702

In [36]:
dataloader = DataLoader(dataset,batch_size=32,num_workers=2, shuffle=True)

In [37]:
# Model Buliding

In [38]:
class LSTMModel(nn.Module):

    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,100,padding_idx=0)
        self.lstm = nn.LSTM(100,150,batch_first=True)
        self.fc = nn.Linear(150,vocab_size)

    def forward(self,x):
        embedded = self.embedding(x)
        intermediate_hidden_states , (final_hidden_state,final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state.squeeze(0))
        return output

In [39]:
model = LSTMModel(len(vocab))

In [40]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [41]:
model.to(device)

LSTMModel(
  (embedding): Embedding(2130, 100, padding_idx=0)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=2130, bias=True)
)

In [42]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters() , lr=learning_rate)

In [43]:
# traing loop

for epoch in range(epochs):
    total_error = 0

    for batch_x , batch_y in dataloader:

        batch_x , batch_y = batch_x.to(device) , batch_y.to(device)

        optimizer.zero_grad()

        output = model(batch_x)

        loss = criterion(output,batch_y)

        loss.backward()

        optimizer.step()

        total_error += loss.item()

    print(f"Epoch : {epoch + 1} ,Loss : {total_error :.4f}")

Epoch : 1 ,Loss : 2565.3291
Epoch : 2 ,Loss : 2246.1346
Epoch : 3 ,Loss : 2005.4425
Epoch : 4 ,Loss : 1784.6041
Epoch : 5 ,Loss : 1578.5705
Epoch : 6 ,Loss : 1390.3453
Epoch : 7 ,Loss : 1211.7892
Epoch : 8 ,Loss : 1048.1060
Epoch : 9 ,Loss : 905.0290
Epoch : 10 ,Loss : 784.2106
Epoch : 11 ,Loss : 671.1470
Epoch : 12 ,Loss : 576.0847
Epoch : 13 ,Loss : 495.1068
Epoch : 14 ,Loss : 424.0568
Epoch : 15 ,Loss : 363.6675
Epoch : 16 ,Loss : 313.3207
Epoch : 17 ,Loss : 270.3642
Epoch : 18 ,Loss : 238.9689
Epoch : 19 ,Loss : 208.6181
Epoch : 20 ,Loss : 181.1756
Epoch : 21 ,Loss : 161.8255
Epoch : 22 ,Loss : 146.8556
Epoch : 23 ,Loss : 139.2807
Epoch : 24 ,Loss : 126.5484
Epoch : 25 ,Loss : 118.8881
Epoch : 26 ,Loss : 112.0420
Epoch : 27 ,Loss : 108.2980
Epoch : 28 ,Loss : 105.2136
Epoch : 29 ,Loss : 102.2093
Epoch : 30 ,Loss : 103.2707
Epoch : 31 ,Loss : 96.8175
Epoch : 32 ,Loss : 93.6193
Epoch : 33 ,Loss : 90.7990
Epoch : 34 ,Loss : 89.2212
Epoch : 35 ,Loss : 88.8544
Epoch : 36 ,Loss : 87.6674

In [45]:
def prediction(model , vocab , text):
    model.eval()

    tokenized_text = word_tokenize(text.lower())

    # text --> numberical index

    numberical_text = text_to_indices(tokenized_text,vocab)

    # padding
    padded_seq = [0] * (61 - len(numberical_text)) + numberical_text
    padded_text = torch.tensor(padded_seq,dtype=torch.long).unsqueeze(0)

    padded_text = padded_text.to(device)


    # send model

    output = model(padded_text)

    # predicted index
    value , index = torch.max(output,dim=1)

    # merge with text
    return text + " " + list(vocab.keys())[index]

In [46]:
prediction(model,vocab,"Microsoft released a new version")

'Microsoft released a new version of'

In [57]:
import time

num_tokens = 100
input_text = "It's a little bit better"

for i in range(num_tokens):
    output_text = prediction(model,vocab,input_text)
    print(output_text)
    input_text = output_text

It's a little bit better at
It's a little bit better at reasoning
It's a little bit better at reasoning very
It's a little bit better at reasoning very slightly
It's a little bit better at reasoning very slightly better
It's a little bit better at reasoning very slightly better at
It's a little bit better at reasoning very slightly better at computer
It's a little bit better at reasoning very slightly better at computer use
It's a little bit better at reasoning very slightly better at computer use and
It's a little bit better at reasoning very slightly better at computer use and you
It's a little bit better at reasoning very slightly better at computer use and you know
It's a little bit better at reasoning very slightly better at computer use and you know just
It's a little bit better at reasoning very slightly better at computer use and you know just fairly
It's a little bit better at reasoning very slightly better at computer use and you know just fairly modest
It's a little bit bett

In [52]:
# evalute
dataloader1 = DataLoader(dataset,batch_size = 32, shuffle=True)

In [56]:
def calculate_accuracy(model,dataloader,device):
    model.eval()

    total = 0
    correct = 0

    with torch.no_grad():
        for batch_x,batch_y in dataloader:
            batch_x,batch_y = batch_x.to(device) , batch_y.to(device)

            # model
            output = model(batch_x)

            # get the predicted words index
            _ , prediction = torch.max(output,dim=1)

            # Compare with actual labels
            correct += (prediction == batch_y).sum().item()
            total += batch_y.size(0)
    accuracy = correct / total * 100
    return accuracy

accuracy = calculate_accuracy(model,dataloader,device)
print(f"Model Accuracy : {accuracy}")

Model Accuracy : 94.34734687450795
